MAX_PIXELS=151200 RESIZED_HEIGHT=360 RESIZED_WIDTH=420 NFRAMES=60 NPROC_PER_NODE=8 swift sft \
  --model_type qwen2-vl-7b-instruct \
  --model_id_or_path /gruntdata/heyuan2/workspace/bobblair.wj/zqp/Qwen__Qwen2-VL-7B-Instruct \
  --sft_type lora \
  --dataset data/sft_dataset_cv/train.jsonl \
  --deepspeed default-zero2 \
  --lora_rank 8 \
  --lora_alpha 16 \
  --target_modules AUTO \
  --learning_rate 1e-4 \
  --gradient_accumulation_steps 4 \
  --freeze_vit True \
  --eval_steps 200 \
  --logging_steps 5 \
  --batch_size 1 \
  --dataloader_num_workers 20 \
  --push_to_hub False \
  --num_train_epochs 2 \