ps -ef | grep swift | grep -v grep | awk '{print "sudo kill -9 "$2}' | sh
MAX_PIXELS=100352 NPROC_PER_NODE=8 swift sft \
  --model_type qwen2-vl-7b-instruct \
  --model_id_or_path /gruntdata/heyuan67/huoluo.wx/models/Qwen__Qwen2-VL-7B-Instruct \
  --sft_type full \
  --dataset /gruntdata/heyuan67/zqp/MIX_MPDOC_DUDE_NEWSVQA/qwen2vl_swift_train_mpdocvqa_dude_newsvqa.jsonl \
  --deepspeed ds_z3_config.json \
  --target_modules AUTO \
  --learning_rate 1e-6 \
  --gradient_accumulation_steps 1 \
  --freeze_vit False \
  --logging_steps 1 \
  --batch_size 1 \
  --output_dir /gruntdata/heyuan67/zqp/qp_lm_models/mpdocvqa_dude_newsvqa/1e-6 \
  --dataloader_num_workers 8 \
  --save_safetensors True \
  --save_only_model True \
  --gradient_checkpointing True \
  --save_strategy epoch \
  --push_to_hub False \
  --use_flash_attn True \
  --dataset_test_ratio 0. \
  --num_train_epochs 10 \
  --save_total_limit 10 \
